### ISSUE TITLE
Add how to install valgrind and clang-format on CONTRIBUTING.md

### ISSUE THREAD

**Issue by ArielMAJ** [ArielMAJ/test.me#159]
- [x] Add it to "Local Development" section in CONTRIBUTING.md;
- [x] Remove how to install valgrind/clang-format from main README.
- [x] Explain that `make valgrind` and `make format` must always be run before commiting/making PRs

**Comment by PoulasthaMukherjee** [comment]
Assign me this issue @ArielMAJ

**Comment by ArielMAJ** [comment]
> Assign me this issue @ArielMAJ

Done

**Comment by PoulasthaMukherjee** [comment]
@ArielMAJ Also, could you add the gssoc23 label to this issue please? I'm a contributor.

**Comment by ArielMAJ** [comment]
I'll take a look at it once I have some free time

**Comment by ArielMAJ** [comment]
Label added. Lmk if we can help you with anything else.

**Comment by PoulasthaMukherjee** [comment]
@ArielMAJ @tauanesales Thank you!
